### PR TITLE
TOD Updates 9

### PR DESCRIPTION
**Pull request by kdmxp256**
- Update the Facility Hub Wardens and ensure their associated Facility hub quests are present
- Add updated quests from LSD quests.json
- Add remaining spells from spells.json
- Updated Old Nectar and Ancient Shard of Metal and ensured their associated quests are present
- Renamed the Level8Spells Patches sub directory, as there are more than just level 8 spells therein

### CODE REVIEW

**Comment by gmriggs** [comment]
Were the rest of the spells compared with the existing database?

**Comment by kdmxp256** [comment]
Level8Spells is inaccurate, as there is more than just level 8 spells within.

The spells added to this update folder aren't replacing anything.  The ones that I added are filling in the missing gaps.  I filtered out all of the spells that were already in the database from the spells.json extract that I performed.

**Comment by gmriggs** [comment]
So name it 'Level8AndMoASpells'

**Comment by kdmxp256** [comment]
Restructuring and rebuilding; will post a new PR

**Pull request closed without merging**
