### PR TITLE
Add support for First Contact Contract

### PR DESCRIPTION
**Pull request by jrock75**
Please provide commits, if I'm not doing this correctly. Thanks!

### CODE REVIEW

**Comment by ziang4891** [comment]
This change is not complete.  The table needs to be updated, and this quest also qualifies for the Contract for Broker Contracts quest.

**Comment by jrock75** [comment]
I don't know which table needs to be updated. 

Not sure how to Contract for Broker Contracts part :(

Should I just close it?

**Comment by ziang4891** [comment]
I am working on the update, now

**Comment by jrock75** [comment]
Thanks

**Pull request closed without merging**
