### PR TITLE
Add support for trinket tinkering, Focusing Lenses and Horns of Leadership. Update vendor NPCs

### PR DESCRIPTION
**Pull request by DridsGhost**
This is a working PR. I will add support for the focusing lenses, medals and virindi essence devices at a later date.

### CODE REVIEW

**Comment by DridsGhost** [comment]
Almost forgot. We still need spell support for the following

SpellID | Icon | Name | Description | Level | School | Category
-- | -- | -- | -- | -- | -- | --
5122 |   | Call of Leadership V | Increases maximum health by 10 points for 30 minutes. | 8 | Life | LeadershipHealthRaising
5133 |   | Call of Leadership I | Increases maximum health by 2 points for 30 minutes. | 4 | Life | LeadershipHealthRaising
5134 |   | Call of Leadership II | Increases maximum health by 4 points for 30 minutes. | 5 | Life | LeadershipHealthRaising
5135 |   | Call of Leadership III | Increases maximum health by 6 points for 30 minutes. | 6 | Life | LeadershipHealthRaising
5136 |   | Call of Leadership IV | Increases maximum health by 8 points for 30 minutes. | 7 | Life | LeadershipHealthRaising

**Comment by ziang4891** [comment]
The step 3 recipes for the moderate and minor imbues might be missing the application of the IconUnderlay, if they are supposed to have that added, like the Major ones get.  The step 2 recipes for the moderate and minor imbues are applying the IconUnderlay for the output object.  It is only the final trinket imbue application, for the moderate and minor, that are missing the underlay

**Comment by DridsGhost** [comment]
Are we good to go with this then?

**Comment by ziang4891** [comment]
ItemCurMana should match ItemMaxMana on the lens caster items; Recipe 8478's cookbook has the wrong target wcid

**Pull request merged**
