### PR TITLE
NPC Placeholders and Other Items

### PR DESCRIPTION
**Pull request by ziang4891**
- Remove unnecessary quests and Viamontian Man-at-Arms weenie from F&F patch
- Add dressed NPC placeholders created by OptimShi and set spawn locations
- Remove the 05693 Bretself the Translator.sql  and 19713 Ciandra, Arcanum Alchemist.sql partial insert files and added fragment data into full weenie files
- SQL formatting cleanup

### CODE REVIEW

**Comment by DridsGhost** [comment]
Looks like you cleaned up some of my stuff. I appreciate that. Moving the burning sands keyring, and adjusted the skillcheck. Why change the recipe ID? I dont have a handle on the current ranges, was just working from that block. 

Probably should get rid of all the 0511count quests, thats a left over. Anything else with count on it should NOT be touched.

**Comment by ziang4891** [comment]
Yeah, I forgot about those extra quest counters.

I don't think I actually renumbered any of the recipes.  I just added a leading zero to match the current files, so they order themselves correctly.

**Comment by DridsGhost** [comment]
Database/Patches/2013-02-BalanceOfPower/4 CraftTable/8360 Shattered Legendary Key.sql → Database/Patches/2013-02-BalanceOfPower/4 CraftTable/08060 Aged Legendary Key.sql

The recipe number is changed. And difficulty. Looks like its set for 50%. That the rule of thumb?

**Comment by ziang4891** [comment]
I didn't notice that they were essentially the same recipe

**Pull request merged**
