### PR TITLE
Update rewards for Suzuhara Baijin's Delivery

### PR DESCRIPTION
**Pull request by ccressent**
First time contributor here and I would appreciate if you could review and give me guidance for future contributions.

The [wiki page for the quest](https://asheron.fandom.com/wiki/Suzuhara_Baijin's_Delivery) mentions 1 MMD note is also part of the final reward, but I'm not sure when that happened.

It's also mentioned that the repeat time for the quest was reduced to 20 hours with 'The Quest for Freedom', but it looks like the timer has already been set to 20 hours as part of b048b5597 (2015-07-ThroneOfDestiny). Should that be changed to only happen in 'The Quest for Freedom'?

### CODE REVIEW

**Comment by ziang4891** [comment]
In ACE World Patches, the full weenie files are used and updated, rather than performing a simple update script.  The Trade Note is given when the player receives the Suzuhara's Girth of Flame Protection, after handing the **Note to Baijin** to Suzuhara Baijin.

**Comment by gmriggs** [comment]
Hey @ccressent 

Thanks for the contribution!

As @ziang4891 mentioned, to update 30386 and 30387, the original .sql files should be edited to have all of the newest data in the Insert statements, and then update the last_Modified datestamp at the top of the file

When a new version of the World database is released, there are build scripts that run on github that pull in all of the files from ACE-World-16PY, and then it builds the full combined database. Individual update scripts might run in an unknown order, so usually we just edit the original files. This also makes tracking the full revision path / latest data for a particular weenie easier -- when someone searches for 30386 and 30387, they see the latest version of the data all in 1 file, and the last time it was updated. And if they want to see the full history of updates, that's all in the git history for that file too

**Comment by ccressent** [comment]
Thank you very much for the detailed explanation! I'll make the changes that you guys recommend: if I understand correctly, you'd rather have me update [30386 Suzuhara Sheshumi.sql](https://github.com/ACEmulator/ACE-World-16PY/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/Creature/Human/30386%20Suzuhara%20Sheshumi.sql) and [30387 Suzuhara Baijin.sql](https://github.com/ACEmulator/ACE-World-16PY/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/Creature/Human/30387%20Suzuhara%20Baijin.sql) in the ACE-World-16PY repo?

The folder layout of this project gave me the impression that the idea was to ultimately be able to apply patches up to a certain point in time rather than an "all or nothing" approach. For example, base game + all patches up to October 2008.

Doesn't modifying the "original" sql files for the weenies directly prevent this and forces server admins to just have the latest version of everything? I'm asking in order to better understand the goals and philosophy behind the project in order to hopefully better contribute; thanks again!

**Comment by gmriggs** [comment]
Ah that's another thing -- if those wcids were originally in the base ACE-World-16PY repo, and then they were later updated after 16PY, the updated version would be created/modified in this -Patches repo

Yes, someone can build any version of the full combined database, up to any point in time, picking and choosing which patches to apply.

**Comment by gmriggs** [comment]
Another small detail -- if for example an object was added in 2007, and then updated in 2008, and again in 2009  -- the Lifestoned content creators are just creating the final version of the objects for the patch they were introduced.

**Comment by ziang4891** [comment]
I would suggest copying the two NPC files from ACE-World-16PY and place them in an appropriate patch level folder in ACE-World-Patches

**Comment by ziang4891** [comment]
Nice

**Pull request merged**
