### PR TITLE
Update 44017 Tamed Armoredillo.sql

### PR DESCRIPTION
**Pull request by sapphire-knight**
Add Mangled Dark Key to possible loot drop

http://acpedia.org/wiki/Tamed_Armoredillo
https://asheron.fandom.com/wiki/Tamed_Armoredillo

### CODE REVIEW

**Review by ziang4891 — APPROVED** [review]

**Comment by DridsGhost** [comment]
Do we have any data outside of the wiki? Over 304 items recorded and no mangled key is shown

https://github.com/ACEmulator/ACE-PCAP-Exports/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/Creature/Armoredillo/44018%20Tamed%20Armoredillo.sql

**Comment by TectonicRifts** [comment]
The mangled dark keys should be vod creatures only. I don't remember anything in neftet dropping them.

**Comment by sapphire-knight** [comment]
http://www.trophyhunteronline.com/monster-trophy.php?monster=Tamed+Armoredillo

**Comment by LtRipley36706** [comment]
closing this for now

**Pull request closed without merging**
