### PR TITLE
Tome casters from 2009-02-UnfinishedBusiness

### PR DESCRIPTION
**Pull request by bobigor377**
ready for review

https://asheron.fandom.com/wiki/Tome_of_Chill

https://asheron.fandom.com/wiki/Tome_of_Caustics

https://asheron.fandom.com/wiki/Tome_of_Flame

### CODE REVIEW

**Comment by ziang4891** [comment]
Signed off from me

**Comment by LawrencePW** [comment]
The value of Tome of Chill is 15 and should be 10.
All other things looks good for me.

**Comment by ziang4891** [comment]
Value in the PCAP is 15

**Comment by LawrencePW** [comment]
https://asheron.fandom.com/wiki/Tome_of_Chill
this shows a value of 10. Last time I should refer to this. Is this now changed ?
Why is the value of the 2 other 10 in pcap and 15 for this one? Does this makes sense. For me it looks similar the same except the spells.

**Comment by ziang4891** [comment]
They are sold by different alt currency vendors.  Besides which, PCAP trumps wiki

**Pull request merged**
