### PR TITLE
WIP: Pet Shop Quest

### PR DESCRIPTION
**Pull request by bobigor377**
TODO
Larinne Kerendova npc needs appearance/dressed
Fix Quest emote chain

Wiki Reference, 
https://asheron.fandom.com/wiki/Pet_Shop_Quest

Video Reference, 
https://www.twitch.tv/videos/24319512

### CODE REVIEW

**Comment by ziang4891** [comment]
Many files need some cleanup, such as removing the properties like weenie_properties_palette, weenie_properties_texture_map, and weenie_properties_anim_part.  Using those properties to obtain the NPC's looks is not kosher.  Also, properties in the 8k range, such as PCAPRecordedLocation, are not needed, as they are stripped in the final build process.

**Comment by ziang4891** [comment]
This PR is going to have some conflict with pending PR 303, as that one also has the Sword of Bellenese quest items

**Comment by bobigor377** [comment]
> 
> 
> This PR is going to have some conflict with pending PR 303, as that one also has the Sword of Bellenese quest items

That's fine, this is a very work in progress. I can update the PR as needed when PR 303 is merged in. Was working on it locally and figured I would post what I had.

**Comment by bobigor377** [comment]
Possible for anyone to take a look at this and see why it's not working? Per the wiki, the npc should tell "Hurry back with the responses from the others. Thanks again!" when you hand in a reply letter but aren't finished yet. The quest success is working when you reach all items, but the quest failure does not. Hence no tell saying hurry back 

https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/e55eeb797a9d4ca5fcd860562bffb0ba4016069e/Database/Patches/2006-09-ComeWhatFollows/9%20WeenieDefaults/Creature/Human/33939%20Larinne%20Kerendova.sql#L112-L139

**Comment by ziang4891** [comment]
You need three quest entries, the cool-down, the counter, and a third that flags the player as being on the quest.  You cannot use the counter for the flag.  InqQuestSolves and InqQuest kind of interfere with each other, in chaining to the QuestSuccess/QuestFailure.  Also, there should be a quest in progress check, on the Use to prevent the letters being handed out multiple times.  Lastly, should probably be using StampQuest, when handing in the replies, instead of IncrementQuest, and SetQuestCompletions to 0, instead the initial IncrementQuest.

**Pull request closed without merging**
