### PR TITLE
Gurog Ice Cave Fix

### PR DESCRIPTION
**Pull request by sLackeR-hub**
Changed Loot Tier to 7.

### CODE REVIEW

**Comment by Schneebs** [comment]
This modifies the wcid's used for the outside FV generator as well and would break the outdoor area.

https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/master/Database/Patches/9%20WeenieDefaults/Generic/None/70358%20Outside%20SV%20Gen.sql

**Comment by Schneebs** [comment]
Took another look through them...  

The following should continue to drop t8 and give lum:
43391 Gurog Minion (remove changes)
43392 Gurog Henchman  (remove changes)
43393 Gurog Soldier  (remove changes)
43689 Frozen Wight Captain (remove changes)
43690 Frozen Wight  (remove changes)
43691 Frozen Wight Sorcerer (remove changes)
51316 Frozen Wight Archer (remove changes)

Other updates:
43396 Gurog Soldier - in addition to t7, should also be no lum (needs updated)
43823 Frozen Wight Sorcerer.sql - should be t7 (needs updated)
45008 Frozen Wight Sorcerer.sql - should be t7 (needs updated)

I also have a branch with these changes if you'd rather me do a PR instead.

**Comment by sLackeR-hub** [comment]
43394, 43395, 43396, 43516, 70361 are all in the cave. Updated the rest.

**Comment by Schneebs** [comment]
Updates look correct - thanks!

**Pull request merged**
