### PR TITLE
Shields sold by Lintareal 

### PR DESCRIPTION
**Pull request by bobigor377**
ready for review

https://asheron.fandom.com/wiki/Shield_of_the_Gold_Gear

https://asheron.fandom.com/wiki/Aegis_of_the_Gold_Gear

### CODE REVIEW

**Comment by ziang4891** [comment]
Since these two shields are purchased with alternate currency, I think they should probably be DestroyOnSell, so they don't end up on another vendor selling for Pyreal coin

**Comment by DridsGhost** [comment]
Do we need the following because the shield can be casted on?

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (43140,  11, True ) /* IgnoreCollisions */
     , (43140,  13, True ) /* Ethereal */
     , (43140,  14, True ) /* GravityStatus */
     , (43140,  19, True ) /* Attackable */
     , (43140,  22, True ) /* Inscribable */;

**Comment by ziang4891** [comment]
Attackable = true is the default and IgnoreCollisions, Ethereal, and GravityStatus are covered by PropertyInt 93

**Comment by DridsGhost** [comment]
These do not seem necessary?
     , (43140, 159,          1) /* WieldSkillType - Axe */
     , (43140, 160,        180) /* WieldDifficulty */

**Pull request merged**
