### PR TITLE
Fleshed out all alchemical throwing phials and crafting recipes, brings up to EOR state

### PR DESCRIPTION
**Pull request by adamplumb**
Here is my attempt at fleshing out the alchemical throwing phials, and bringing them to what seems to be the end of retail state.  I've created new recipes starting from 8940 and going to 9058.  I've also updated some properties of the phials to bring them up to date, including:

- Updated the melee defense modifiers to a graduated scale from +0% to +14% [1].  I don't have any hard evidence that the melee d scales like this but the Levistras wiki [2] does seem to support this.
- Phial unit burden was originally 15 then was reduced to 10 in 2009-12-GainingGround [3], then again to 5 at some point later as evidenced by [1]
- Value of uncrafted phials was reduced by half in 2009-12-GainingGround [3]
- Fester phials were added in 2009-12-GainingGround [3]
- Stack size increased to 250 in 2009-12-GainingGround[3]

I've gone through and crafted each phial from peas and individual phials and confirmed they're working.  I've also used all existing weenies where possible and updated them as necessary.

Evidence:
[1] http://acpedia.org/wiki/File:Mana_Phial_of_Imperil.jpg
[2] https://acportalstorm.com/wiki/Alchemical_Throwing_Phials
[3] http://acpedia.org/wiki/Alchemical_Throwing_Phials

Not yet implemented, but I just saw on the levistras wiki [2] some other updates that I didn't see until just now:
```
Unknown:
    Crafting using single ingredients (rather than peas) produces 5 phials, increased from 1.
    Crafting using peas producers 250, increased from 50.
```
So I'm thinking maybe I should include those updates here as well, what do you think?

Update, since I saw those changes on fandom as well, and it makes sense given the further burden decrease in GainingGround, I went ahead and updated the recipes to create 5 phials for the individual recipe and 250 for the peas.

### CODE REVIEW

**Review by ziang4891 — CHANGES_REQUESTED** [review]
- The numbers in the file names should be the recipe ID numbers, not the wcid number of the output product
- There are already recipes for the Imperil phials and the full set of Mana phials.  They don't need to be recreated.  If the need adjusting, change the existing ones

**Review by adamplumb — COMMENTED** [review]
OK I updated with a few more things:

1. Merged new recipes and existing and updated filenames to point to the recipe id
2. Re-used existing weenies, tweaking where necessary

Retested on a freshly imported db, and it seems to be working well.

**Comment by adamplumb** [comment]
Hey I just wanted to check in on this and see if there is anything else you are waiting for from me or if there is anything I can do.  If you just haven't gotten to it yet that's fine too.

**Comment by adamplumb** [comment]
Hi I just wanted to check in about this. It has been a couple weeks since I
resolved your change requests. I can understand if you're busy and haven't
had time to commit to this. But let me know if I can help make the process
go smoother. I realize this PR touches a lot of files so I could try to
split it up if desired.  I'm happy to work with you to get it merged.
Thanks!

**Review by ziang4891 — APPROVED** [review]

**Pull request merged**
