### PR TITLE
Portals Not yet Implemented 33035, 35038, 43118, 43119, 43120, 43536, 43559, 43580, 43705

### PR DESCRIPTION
**Pull request by lugielord**
The portals in this PR are 'not yet implemented', they need destination coords set.
33035, 35038, 43118, 43119, 43120, 43536, 43559, 43580, 43705

### CODE REVIEW

**Comment by lugielord** [comment]
Ok, I'm done with 'not yet implemented' portals.  Hope these are simple to review.

**Comment by jovrtn** [comment]
Looks like this PR only includes changes to three wcids -- 35038, 43536, 43580 -- but there are 9 mentioned in the title + description?

**Comment by TectonicRifts** [comment]
The destination for 35038 But Catacombs is not correct. It should be:

0x00D40535 [120.000000 -210.000000 -11.985000] 1.000000 0.000000 0.000000 0.000000

See here for pcap portal destinations: https://docs.google.com/spreadsheets/d/122xOw3IKCezaTDjC_hggWSVzYJ_9M_zUUtGEXkwNXfs/edit#gid=1982943263

**Comment by lugielord** [comment]
I'll close this PR and make the fix in my other one, since this is now redundant.

**Comment by lugielord** [comment]
Moved changes and review comment fixes into #1643.

**Pull request closed without merging**
