### PR TITLE
Update Atlan and Isparian Weapons to have WeaponType

### PR DESCRIPTION
**Pull request by Zurgash**
Missing weapon times preventing tailoring to happen

### CODE REVIEW

**Comment by ziang4891** [comment]
This PR will not be accepted, as it is not retail.  These weapons did not have a WeaponType

**Comment by Zurgash** [comment]
Ooh okay, still learning what to check here. I was going off of the Fandom site and it shows it there

**Comment by ziang4891** [comment]
Don't trust the wiki over PCAP'ed data

**Comment by Zurgash** [comment]
Thanks! I will kill this PR. Much appreciated!

**Pull request closed without merging**
